site_name: NearIT Xamarin
theme: readthedocs
extra_css : ["css/nearitdocs.css"]
extra_javascript : ["js/extra.js"]
pages:
    - 'Getting started' : 'index.md'
    - 'Portable Class Library' :
        - 'Permissions Request' : 'bridge/permissions.md'
        - 'Coupon Detail' : 'bridge/coupon.md'
        - 'Feedback Detail' : 'bridge/feedback.md'
        - 'Content Detail' : 'bridge/content.md'
        - 'Coupon List' : 'bridge/couponList.md'
    - 'iOS' :
        - 'Permissions Request' : 'ios/permissions.md'
        - 'Coupon Detail' : 'ios/coupon.md'
        - 'Feedback Detail' : 'ios/feedback.md'
        - 'Content Detail' : 'ios/content.md'
        - 'Coupon List' : 'ios/couponList.md'
    - 'Android' :
        - 'Permissions Request' : 'android/permissions.md'
        - 'Coupon Detail' : 'android/coupon.md'
        - 'Feedback Detail' : 'android/feedback.md'
        - 'Content Detail' : 'android/content.md'
        - 'Coupon List' : 'android/couponList.md'
        - 'Advanced' : 'android/advanced.md'

